### ISSUE TITLE
Using flutter distributor with FVM

### ISSUE THREAD

**Issue by werner-scholtz** [leanflutter/flutter_distributor#191]
Hi, is there a way to configure flutter_distributor to run all flutter commands with [fvm](https://fvm.app/documentation/guides/running-flutter) ?
ex. `fvm flutter run`, `fvm flutter build`

**Comment by cybrox** [comment]
AFAIK there is currently no way to easily override the command that is used by `flutter_distributor`.

I don't use `fvm` myself but [their docs state](https://fvm.app/documentation/guides/running-flutter#call-sdk-directly) that the active version is symlinked to `.fvm/flutter_sdk/bin/flutter`. If that's the case, you can use the `FLUTTER_ROOT` environment variable that is supported by `flutter_distributor` [here](https://github.com/leanflutter/flutter_distributor/blob/4a8384e48a562bca652e1f9b3073e18999688f9d/packages/flutter_app_builder/lib/src/commands/flutter.dart#L56).

So instead of `flutter_distributor release ...` you would use `FLUTTER_ROOT=.fvm/flutter_sdk flutter_distributor release ...`.

**Comment by lijy91** [comment]
Please see: https://github.com/leanflutter/flutter_distributor/issues/107#issuecomment-1570480975

**Comment by werner-scholtz** [comment]
Thanks for the epic package :D
